# Generated by Django 5.1.1 on 2024-09-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managemoney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
