# Generated by Django 5.1.1 on 2024-10-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemoney', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
