# Generated by Django 5.1.1 on 2024-10-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managemoney', '0004_budget_expense_income_savings_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savings',
            new_name='Saving',
        ),
    ]
